### PR TITLE
Use supertest to test api

### PR DESCRIPTION
**Pull request by oscar-g**
- Saves a few lines, runs tests slightly faster, and tests are more readable.
- Fixes npm test script

### CODE REVIEW

**Comment by evanplaice** [comment]
@oscar-g This setup tests directly against the Express routes and not a live server.
```

**Comment by oscar-g** [comment]
What is the difference, technically? As far as I know, supertest is an
accurate way to test an express server.

Practically, a live server and the route functions are equivalent: when a
live server receives a request, it runs the code loaded into that route.

Maybe I'm not understanding what you mean? How would testing a live server
be different than testing the route?

**Comment by evanplaice** [comment]
@oscar-g I removed the previous comment because it wasn't really relevant.

BTW, nice job on the quick conversion to SuperTest. The test code is so much cleaner and I already managed to track down a bug on the PUT route when I was writing the test.

**Comment by oscar-g** [comment]
Ahh, ok. I was confused!
Thanks!

**Pull request merged**
